"use client";

import { use, useState } from "react";
import { motion } from "framer-motion";
import {
  BookOpen,
  FileText,
  Database,
  FolderTree,
  Server,
  Rocket,
  Copy,
  Check,
  Download,
} from "lucide-react";

type DocType = "readme" | "api" | "architecture" | "folders" | "database" | "setup" | "deployment";

const docs: Record<DocType, { title: string; icon: React.ElementType; description: string; content: string }> = {
  readme: {
    title: "README",
    icon: FileText,
    description: "Project overview and quick start guide",
    content: `# my-nextjs-app

> A Next.js 15 application with TypeScript, Tailwind CSS, and PostgreSQL.

## Quick Start

\`\`\`bash
git clone https://github.com/owner/my-nextjs-app.git
cd my-nextjs-app
npm install
cp .env.example .env
npm run dev
\`\`\`

## Features

- 🔐 JWT-based authentication with httpOnly cookies
- 📊 Interactive dashboard with real-time analytics
- 🗄️ PostgreSQL with Drizzle ORM (type-safe queries)
- 🎨 Tailwind CSS with custom design system
- 📱 Responsive design for all screen sizes
- 🔄 RESTful API with 12 endpoints
- 🛡️ Auth middleware for protected routes

## Tech Stack

| Technology | Version | Purpose |
|---|---|---|
| Next.js | 15 | React framework with App Router |
| React | 19 | UI library with Server Components |
| TypeScript | 5.x | Static type checking |
| Tailwind CSS | 4.x | Utility-first CSS |
| Drizzle ORM | 0.45 | Type-safe database queries |
| PostgreSQL | 16 | Relational database |
| jsonwebtoken | 9.x | JWT authentication |
| Framer Motion | 11 | Animations |

## Project Structure

\`\`\`
src/
├── app/              → Pages & API routes
├── components/       → Reusable UI components
├── lib/              → Utilities & shared logic
└── db/               → Database schema & connection
\`\`\`

## Environment Variables

| Variable | Required | Description |
|---|---|---|
| DATABASE_URL | Yes | PostgreSQL connection string |
| JWT_SECRET | Yes | Secret key for JWT signing |
| NODE_ENV | Yes | Application environment |

## Scripts

| Command | Description |
|---|---|
| \`npm run dev\` | Start development server |
| \`npm run build\` | Build for production |
| \`npm start\` | Start production server |
| \`npm run lint\` | Run ESLint |
| \`npm run typecheck\` | Run TypeScript check |

## License

MIT

---
*Generated by HELIOS AI*`,
  },
  api: {
    title: "API Documentation",
    icon: Server,
    description: "Complete API reference with request/response examples",
    content: `# API Documentation

Base URL: \`http://localhost:3000/api\`

## Authentication

All protected endpoints require a valid JWT token in an httpOnly cookie named \`auth-token\`.

### POST /api/auth

Authenticate a user and receive a JWT token.

**Request:**
\`\`\`json
{
  "email": "user@example.com",
  "password": "secure-password"
}
\`\`\`

**Response (200):**
\`\`\`json
{
  "user": {
    "id": "uuid",
    "name": "John Doe",
    "email": "user@example.com",
    "role": "user"
  }
}
\`\`\`

**Response (401):**
\`\`\`json
{
  "error": "Invalid credentials"
}
\`\`\`

---

### GET /api/users

List all users. **Requires authentication.**

**Response (200):**
\`\`\`json
[
  {
    "id": "uuid",
    "name": "John Doe",
    "email": "john@example.com",
    "role": "user",
    "createdAt": "2024-01-15T10:30:00Z"
  }
]
\`\`\`

---

### POST /api/users

Create a new user. **Requires authentication.**

**Request:**
\`\`\`json
{
  "name": "Jane Doe",
  "email": "jane@example.com",
  "password": "secure-password"
}
\`\`\`

**Response (201):**
\`\`\`json
{
  "id": "uuid",
  "name": "Jane Doe",
  "email": "jane@example.com",
  "role": "user"
}
\`\`\`

---

### GET /api/health

Health check endpoint. **No authentication required.**

**Response (200):**
\`\`\`json
{
  "status": "ok",
  "timestamp": "2024-01-15T10:30:00Z"
}
\`\`\`

---

### GET /api/projects

List all projects for authenticated user. **Requires authentication.**

### POST /api/projects

Create a new project. **Requires authentication.**

### GET /api/projects/:id

Get project by ID. **Requires authentication.**

### DELETE /api/projects/:id

Delete a project. **Requires authentication.**

### GET /api/admin/stats

Admin statistics. **Requires admin role.**`,
  },
  architecture: {
    title: "Architecture Docs",
    icon: BookOpen,
    description: "System architecture and design decisions",
    content: `# Architecture Documentation

## Overview

This application follows the Next.js App Router architecture with a clear separation between server and client components.

## High-Level Architecture

\`\`\`
┌─────────────┐
│   Client     │  React 19 + Tailwind CSS
│  (Browser)   │  Framer Motion animations
└──────┬───────┘
       │ HTTP
┌──────▼───────┐
│  Next.js     │  App Router + Server Components
│  Server      │  API Routes + Middleware
└──────┬───────┘
       │
  ┌────┼────┐
  │    │    │
  ▼    ▼    ▼
Auth  API  ORM
JWT   REST  Drizzle
  │    │    │
  └────┼────┘
       │
┌──────▼───────┐
│  PostgreSQL  │  Primary database
└──────────────┘
\`\`\`

## Authentication Flow

1. User submits credentials to POST /api/auth
2. Server validates against database
3. JWT token generated with userId and role
4. Token stored in httpOnly cookie (7-day expiry)
5. Middleware verifies token on protected routes
6. Client reads user context from API

## Data Flow

- **Server Components**: Fetch data directly from database
- **Client Components**: Fetch via API routes
- **Mutations**: POST/PUT/DELETE to API routes → ORM → Database
- **Real-time**: Polling with SWR (no WebSockets yet)

## Design Decisions

| Decision | Rationale |
|---|---|
| App Router over Pages | Better layouts, server components, streaming |
| Drizzle over Prisma | Lighter, SQL-like API, better TypeScript inference |
| JWT over Sessions | Stateless, scales horizontally, no session store |
| httpOnly cookies | Prevents XSS access to tokens |
| Zod validation | Type-safe runtime validation shared client/server |`,
  },
  folders: {
    title: "Folder Documentation",
    icon: FolderTree,
    description: "What each directory contains and why",
    content: `# Folder Structure Documentation

## src/app/

Next.js App Router pages and API routes. Each subdirectory maps to a URL path.

- \`page.tsx\` — The page component for this route
- \`layout.tsx\` — Shared layout wrapper for child routes
- \`loading.tsx\` — Loading state (suspense boundary)
- \`error.tsx\` — Error boundary for this route
- \`route.ts\` — API route handler (exports GET, POST, etc.)

### Key Routes

| Path | Purpose |
|---|---|
| / | Landing page |
| /dashboard | Analytics dashboard |
| /import | Project import wizard |
| /api/auth | Authentication endpoint |
| /api/users | User CRUD endpoints |
| /api/projects | Project management |
| /api/health | System health check |

## src/components/

Reusable React components organized by purpose:

- \`ui/\` — Base UI primitives (Button, Card, Input, Badge)
- \`charts/\` — Data visualization components
- \`layout/\` — Structural components (Sidebar, Navbar)

**Convention:** Each component in its own file. Use named exports.

## src/lib/

Shared utilities and business logic:

- \`auth.ts\` — JWT generation and verification
- \`utils.ts\` — General helpers (cn, formatDate, debounce)
- \`analytics.ts\` — Event tracking and reporting

**Rule:** No React imports in lib/ files. Pure functions only.

## src/db/

Database layer using Drizzle ORM:

- \`schema.ts\` — Table definitions and relations
- \`index.ts\` — Database connection and client export

**Rule:** All database access goes through Drizzle queries. No raw SQL.`,
  },
  database: {
    title: "Database Documentation",
    icon: Database,
    description: "Schema, relationships, and query patterns",
    content: `# Database Documentation

## Connection

\`\`\`
postgresql://user:password@localhost:5432/app_db
\`\`\`

Managed via Drizzle ORM. Connection pool configured in \`src/db/index.ts\`.

## Tables

### users

| Column | Type | Nullable | Default | Notes |
|---|---|---|---|---|
| id | UUID | NO | gen_random_uuid() | Primary key |
| name | VARCHAR(255) | NO | — | Display name |
| email | VARCHAR(255) | NO | — | Unique, used for login |
| role | VARCHAR(50) | YES | 'user' | 'user' or 'admin' |
| created_at | TIMESTAMP | NO | now() | Registration time |

### projects

| Column | Type | Nullable | Default | Notes |
|---|---|---|---|---|
| id | UUID | NO | gen_random_uuid() | Primary key |
| name | VARCHAR(255) | NO | — | Project name |
| description | TEXT | YES | — | Optional description |
| tech_stack | JSONB | YES | [] | Detected technologies |
| health_score | INTEGER | YES | 0 | 0-100 health rating |
| status | VARCHAR(50) | YES | 'scanning' | Current scan status |

### project_files

Stores scanned file contents. FK to projects (CASCADE DELETE).

### project_issues

Detected issues per project. FK to projects (CASCADE DELETE).

### chat_messages

AI chat history. FK to projects (CASCADE DELETE).

### api_endpoints

Discovered API endpoints. FK to projects (CASCADE DELETE).

## Relationships

\`\`\`
users 1──N projects (via owner_id)
projects 1──N project_files
projects 1──N project_issues
projects 1──N chat_messages
projects 1──N api_endpoints
\`\`\`

## Common Queries

\`\`\`typescript
// Get project with all relations
const project = await db.query.projects.findFirst({
  where: (p, { eq }) => eq(p.id, projectId),
  with: {
    files: true,
    issues: true,
    endpoints: true,
  },
});

// Get issues by severity
const criticalIssues = await db.query.projectIssues.findMany({
  where: (i, { eq }) => eq(i.severity, "critical"),
});
\`\`\``,
  },
  setup: {
    title: "Setup Guide",
    icon: Rocket,
    description: "Step-by-step local development setup",
    content: `# Setup Guide

## Prerequisites

- Node.js 20+ (recommend using nvm)
- PostgreSQL 16+
- npm or pnpm

## Step 1: Clone Repository

\`\`\`bash
git clone https://github.com/owner/my-nextjs-app.git
cd my-nextjs-app
\`\`\`

## Step 2: Install Dependencies

\`\`\`bash
npm install
\`\`\`

## Step 3: Configure Environment

\`\`\`bash
cp .env.example .env
\`\`\`

Edit \`.env\` with your values:

\`\`\`env
DATABASE_URL=postgresql://postgres:password@localhost:5432/app_db
JWT_SECRET=your-secret-key-here-min-32-chars
NODE_ENV=development
\`\`\`

## Step 4: Set Up Database

\`\`\`bash
# Create database
createdb app_db

# Push schema
npx drizzle-kit push
\`\`\`

## Step 5: Start Development

\`\`\`bash
npm run dev
\`\`\`

Open http://localhost:3000

## Troubleshooting

| Issue | Solution |
|---|---|
| Database connection failed | Check DATABASE_URL and PostgreSQL is running |
| JWT_SECRET error | Ensure JWT_SECRET is set in .env |
| Port 3000 in use | Kill process: lsof -ti:3000 | xargs kill |
| Build errors | Clear .next: rm -rf .next && npm run build |`,
  },
  deployment: {
    title: "Deployment Guide",
    icon: Rocket,
    description: "Production deployment instructions",
    content: `# Deployment Guide

## Vercel (Recommended)

\`\`\`bash
# Install Vercel CLI
npm i -g vercel

# Deploy
vercel --prod
\`\`\`

Set environment variables in Vercel dashboard:
- DATABASE_URL
- JWT_SECRET
- NODE_ENV=production

## Docker

\`\`\`dockerfile
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
EXPOSE 3000
CMD ["npm", "start"]
\`\`\`

\`\`\`bash
docker build -t my-nextjs-app .
docker run -p 3000:3000 --env-file .env my-nextjs-app
\`\`\`

## Environment Checklist

Before deploying to production, ensure:

- [ ] All environment variables are set
- [ ] DATABASE_URL points to production database
- [ ] JWT_SECRET is a strong, unique value (32+ chars)
- [ ] CORS origins are restricted to production domain
- [ ] npm audit passes with no critical vulnerabilities
- [ ] Type checking passes (npm run typecheck)
- [ ] Build succeeds (npm run build)
- [ ] Rate limiting is enabled on auth endpoints

## Monitoring

Recommended monitoring setup:
- Application: Sentry for error tracking
- Performance: Vercel Analytics or DataDog
- Database: pgAdmin or CloudWatch
- Uptime: UptimeRobot or BetterStack`,
  },
};

const docTypes = Object.entries(docs) as [DocType, typeof docs[DocType]][];

export default function DocsPage({ params }: { params: Promise<{ id: string }> }) {
  use(params);
  const [activeDoc, setActiveDoc] = useState<DocType>("readme");
  const [copied, setCopied] = useState(false);

  const currentDoc = docs[activeDoc];

  const copyDoc = () => {
    navigator.clipboard.writeText(currentDoc.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="p-6 md:p-8">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-8">
        <div className="flex items-center gap-3 mb-2">
          <BookOpen className="w-6 h-6 text-accent-400" />
          <h1 className="text-3xl font-bold">Documentation Engine</h1>
        </div>
        <p className="text-helios-400">Auto-generated documentation for every aspect of your project.</p>
      </motion.div>

      <div className="grid lg:grid-cols-4 gap-6">
        {/* Doc Type Selector */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="space-y-2">
          {docTypes.map(([key, doc]) => (
            <button
              key={key}
              onClick={() => setActiveDoc(key)}
              className={`w-full flex items-center gap-3 p-3 rounded-xl text-left text-sm transition-all ${
                activeDoc === key
                  ? "bg-accent-500/10 text-accent-400 border border-accent-500/20"
                  : "text-helios-400 hover:text-helios-200 hover:bg-helios-700/30"
              }`}
            >
              <doc.icon className="w-4 h-4 shrink-0" />
              <div>
                <div className="font-medium">{doc.title}</div>
                <div className="text-xs text-helios-500 mt-0.5">{doc.description}</div>
              </div>
            </button>
          ))}
        </motion.div>

        {/* Doc Preview */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }} className="lg:col-span-3 glass overflow-hidden">
          <div className="flex items-center justify-between px-5 py-3 border-b border-helios-700/50 bg-helios-900/60">
            <div className="flex items-center gap-2">
              <currentDoc.icon className="w-4 h-4 text-accent-400" />
              <span className="text-sm font-medium">{currentDoc.title}</span>
              <span className="badge badge-purple text-[10px]">Auto-generated</span>
            </div>
            <div className="flex items-center gap-2">
              <button onClick={copyDoc} className="flex items-center gap-1.5 px-3 py-1.5 text-xs text-helios-400 hover:text-accent-400 transition-colors">
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? "Copied!" : "Copy"}
              </button>
              <button className="flex items-center gap-1.5 px-3 py-1.5 text-xs text-helios-400 hover:text-accent-400 transition-colors">
                <Download className="w-3.5 h-3.5" /> Export
              </button>
            </div>
          </div>
          <div className="p-6 max-h-[75vh] overflow-y-auto">
            <pre className="whitespace-pre-wrap text-sm font-mono text-helios-200 leading-relaxed">
              {currentDoc.content}
            </pre>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
