"use client";

import { use, useState } from "react";
import { motion } from "framer-motion";
import {
  FileText,
  Copy,
  Check,
  Download,
  RefreshCw,
} from "lucide-react";

const generatedReadme = `# my-nextjs-app

> A Next.js 15 application with TypeScript, Tailwind CSS, and PostgreSQL.

## Features

- 🔐 JWT-based authentication
- 📊 Dashboard with analytics
- 🗄️ PostgreSQL database with Drizzle ORM
- 🎨 Tailwind CSS styling
- 📱 Responsive design
- 🔄 API routes with middleware

## Tech Stack

| Technology | Version | Purpose |
|---|---|---|
| Next.js | 15 | React framework |
| React | 19 | UI library |
| TypeScript | 5.x | Type safety |
| Tailwind CSS | 4.x | Styling |
| Drizzle ORM | 0.45 | Database ORM |
| PostgreSQL | 16 | Database |
| jsonwebtoken | 9.x | JWT authentication |

## Project Architecture

\`\`\`
src/
├── app/              → Next.js App Router pages & API routes
│   ├── page.tsx      → Home page
│   ├── layout.tsx    → Root layout
│   ├── dashboard/    → Dashboard page
│   ├── api/          → API route handlers
│   │   ├── auth/     → Authentication endpoints
│   │   ├── users/    → User management endpoints
│   │   └── health/   → Health check endpoint
│   └── import/       → Project import page
├── components/       → Reusable React components
│   ├── ui/           → Base UI components
│   └── charts/       → Chart components
├── lib/              → Utility functions & shared logic
│   ├── auth.ts       → Authentication helpers
│   └── utils.ts      → General utilities
└── db/               → Database layer
    ├── schema.ts     → Drizzle ORM schema
    └── index.ts      → Database connection
\`\`\`

## Installation

\`\`\`bash
# Clone the repository
git clone https://github.com/owner/my-nextjs-app.git

# Navigate to project directory
cd my-nextjs-app

# Install dependencies
npm install

# Set up environment variables
cp .env.example .env
# Edit .env with your configuration

# Run database migrations
npx drizzle-kit push

# Start development server
npm run dev
\`\`\`

## API Endpoints

| Method | URL | Description | Auth |
|---|---|---|---|
| POST | /api/auth | Authenticate user | No |
| GET | /api/users | List all users | Yes |
| POST | /api/users | Create new user | Yes |
| GET | /api/health | Health check | No |

## Environment Variables

| Variable | Description | Required |
|---|---|---|
| DATABASE_URL | PostgreSQL connection string | Yes |
| JWT_SECRET | Secret key for JWT tokens | Yes |
| NODE_ENV | Application environment | Yes |

## Deployment

\`\`\`bash
# Build for production
npm run build

# Start production server
npm start
\`\`\`

## License

MIT

---

*Generated by [HELIOS AI](https://helios.ai) — The Autonomous Software Engineer*
`;

export default function ReadmePage({ params }: { params: Promise<{ id: string }> }) {
  use(params);
  const [copied, setCopied] = useState(false);
  const [regenerating, setRegenerating] = useState(false);

  const copyReadme = () => {
    navigator.clipboard.writeText(generatedReadme);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const regenerate = () => {
    setRegenerating(true);
    setTimeout(() => setRegenerating(false), 1500);
  };

  return (
    <div className="p-6 md:p-8 max-w-5xl">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-8">
        <div className="flex items-center justify-between">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <FileText className="w-6 h-6 text-accent-400" />
              <h1 className="text-3xl font-bold">README Generator</h1>
            </div>
            <p className="text-helios-400">Auto-generated professional README from your project analysis.</p>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={regenerate}
              disabled={regenerating}
              className="flex items-center gap-2 px-4 py-2 glass glass-hover rounded-xl text-sm transition-all"
            >
              <RefreshCw className={`w-4 h-4 ${regenerating ? "animate-spin" : ""}`} />
              Regenerate
            </button>
            <button
              onClick={copyReadme}
              className="flex items-center gap-2 px-4 py-2 bg-accent-500 hover:bg-accent-400 text-white rounded-xl text-sm transition-all"
            >
              {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              {copied ? "Copied!" : "Copy"}
            </button>
            <button className="flex items-center gap-2 px-4 py-2 glass glass-hover rounded-xl text-sm transition-all">
              <Download className="w-4 h-4" />
              Download
            </button>
          </div>
        </div>
      </motion.div>

      {/* Preview */}
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="glass overflow-hidden">
        <div className="flex items-center gap-2 px-4 py-3 border-b border-helios-700/50 bg-helios-900/60">
          <div className="w-3 h-3 rounded-full bg-rose-500/60" />
          <div className="w-3 h-3 rounded-full bg-amber-500/60" />
          <div className="w-3 h-3 rounded-full bg-emerald-500/60" />
          <span className="ml-3 text-xs text-helios-500 font-mono">README.md</span>
        </div>
        <div className="p-8 max-w-none prose prose-invert prose-sm">
          <pre className="whitespace-pre-wrap text-sm text-helios-200 font-mono leading-relaxed bg-transparent border-0 p-0">
            {generatedReadme}
          </pre>
        </div>
      </motion.div>
    </div>
  );
}
